[package]
name = "oqtopus-cli"
version = "0.0.0"
edition = "2024"
publish = false
autotests = false

[dependencies]
flate2 = "1"
libc = "0.2"
tar = "0.4"
tempfile = "3"
ureq = { version = "3", default-features = false, features = ["rustls"] }

[[bin]]
name = "oqtopus"
path = "src/main.rs"

[[test]]
name = "characterization"
path = "tests/characterization/main.rs"

[[test]]
name = "cli"
path = "tests/cli.rs"

[dev-dependencies]
insta = "1"
