# gRPC settings
proto:
  max_workers: ${GATEWAY_WORKERS, 10} # Maximum number of workers
  address: ${GATEWAY_ADDRESS, "localhost:51021"} # Address and port for RPCs

# Common backend settings
common_backend_settings: &common_backend_settings
  device_info:
    # device_id: "qulacs"
    provider_id: "oqtopus"
    # max_qubits: 16
    max_shots: 10000
  device_status_path: config/gateway/device_status
  device_topology_json_path: config/gateway/device_topology_sim.json

# Backend configuration
default_backend: qulacs  # Available options: "qulacs", "qubex"

# Dependency Injection Container Configuration
backend_di_container:
  registry:
    # QulacsBackend settings
    qulacs:
      _target_: device_gateway.plugins.qulacs.backend.QulacsBackend
      device_type: simulator
      config: *common_backend_settings
    # QubexBackend settings
    qubex:
      _target_: device_gateway.plugins.qubex.backend.QubexBackend
      device_type: QPU
      config: *common_backend_settings
      qubex_config:
        chip_id: ${CHIP_ID, 64Q}
        config_dir: ${CONFIG_DIR, "/app/qubex-config/{chip_id}/config"}
        params_dir: ${PARAMS_DIR, "/app/qubex-config/{chip_id}/params"}
        calib_note_path: ${CALIB_NOTE_PATH, "/app/qubex-config/{chip_id}/calibration/calib_note.json"}
